# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-11 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitativelog',
            name='webClassify',
            field=models.FloatField(default=0),
        ),
    ]
