# Generated by Django 2.1.3 on 2018-11-21 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendModels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urllog',
            name='time',
        ),
        migrations.RemoveField(
            model_name='urllog',
            name='user',
        ),
        migrations.AddField(
            model_name='urllog',
            name='quantitative',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='backendModels.QuantitativeLog'),
        ),
        migrations.AddField(
            model_name='urllog',
            name='times',
            field=models.TextField(null=True),
        ),
    ]
