# Generated by Django 2.1.3 on 2018-12-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendModels', '0002_urllog_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitativelog',
            name='cluster_label',
            field=models.IntegerField(default=0),
        ),
    ]
