# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-12 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendModels', '0002_auto_20180611_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantitativelog',
            name='similarStd',
        ),
        migrations.RemoveField(
            model_name='quantitativelog',
            name='timeSeries',
        ),
        migrations.RemoveField(
            model_name='quantitativelog',
            name='urlSimilarOriginSeries',
        ),
    ]
