# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backendModels', '0003_auto_20180516_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllog',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 5, 16, 12, 44, 8, 351561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='urllog',
            name='urlArgs',
            field=models.TextField(null=True),
        ),
    ]
