# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-25 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendModels', '0004_auto_20180516_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantitativeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar', models.FloatField(default=0)),
                ('urlArgsEntropy', models.FloatField(default=0)),
                ('abnormalTimeProbability', models.FloatField(default=0)),
                ('sameArgsDiversity', models.FloatField(default=0)),
                ('webClassify', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendModels.User')),
            ],
        ),
        migrations.AlterField(
            model_name='urllog',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
