# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-25 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendModels', '0005_auto_20180525_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitativelog',
            name='url',
            field=models.CharField(default=2, max_length=100),
        ),
    ]
