# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-25 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendModels', '0006_quantitativelog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitativelog',
            name='urlSimilarOriginSeries',
            field=models.TextField(null=True),
        ),
    ]
