# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-28 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendModels', '0008_auto_20180526_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitativelog',
            name='timeSeries',
            field=models.TextField(null=True),
        ),
    ]
